/* eslint-disable no-throw-literal */
/* eslint-disable no-empty-function */
module.exports = [
  {
    code: 'wa',
    name: 'Warrior',
    plural: 'Warriors',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: true,
    vetNow: false,
    att: 2,
    def: 2,
    bonus: 1,
    fort: true,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ri',
    name: 'Rider',
    plural: 'Riders',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: true,
    vetNow: false,
    att: 2,
    def: 1,
    bonus: 1,
    fort: true,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ar',
    name: 'Archer',
    plural: 'Archers',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: true,
    vetNow: false,
    att: 2,
    def: 1,
    bonus: 1,
    fort: true,
    range: true,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'de',
    name: 'Defender',
    plural: 'Defenders',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 1,
    def: 3,
    bonus: 1,
    fort: true,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'kn',
    name: 'Knight',
    plural: 'Knights',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 3.5,
    def: 1,
    bonus: 1,
    fort: true,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'sw',
    name: 'Swordsman',
    plural: 'Swordsmen',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 3,
    def: 3,
    bonus: 1,
    fort: true,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ca',
    name: 'Catapult',
    plural: 'Catapults',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: true,
    vetNow: false,
    att: 4,
    def: 0,
    bonus: 1,
    fort: false,
    range: true,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'gi',
    name: 'Giant',
    plural: 'Giants',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 40,
    maxhp: 40,
    vet: false,
    vetNow: false,
    att: 5,
    def: 4,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'cr',
    name: 'Crab',
    plural: 'Crabs',
    group: 'Aquarion',
    groupPriority: 2,
    description: '',
    currenthp: 40,
    maxhp: 40,
    vet: false,
    vetNow: false,
    att: 4,
    def: 4,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'tr',
    name: 'Tridention',
    plural: 'Tridentions',
    group: 'Aquarion',
    groupPriority: 2,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 3,
    def: 1,
    bonus: 1,
    fort: true,
    range: true,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'po',
    name: 'Polytaur',
    plural: 'Polytaurs',
    group: 'Elyrion',
    groupPriority: 3,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 3,
    def: 1,
    bonus: 1,
    fort: true,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'na',
    name: 'Navalon',
    plural: 'Navalons',
    group: 'Elyrion',
    groupPriority: 3,
    description: '',
    currenthp: 30,
    maxhp: 30,
    vet: false,
    vetNow: false,
    att: 4,
    def: 4,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ga',
    name: 'Gaami',
    plural: 'Gaamis',
    group: 'Polaris',
    groupPriority: 4,
    description: '',
    currenthp: 30,
    maxhp: 30,
    vet: false,
    vetNow: false,
    att: 4,
    def: 4,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'mb',
    name: 'Mind Bender',
    plural: 'Mind Benders',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: false,
    vetNow: false,
    att: 0,
    def: 1,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: false,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'eg',
    name: 'Dragon Egg',
    plural: 'Dragon Eggs',
    group: 'Elyrion',
    groupPriority: 3,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: false,
    vetNow: false,
    att: 0,
    def: 2,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: false,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'bd',
    name: 'Baby Dragon',
    plural: 'Baby Dragons',
    group: 'Elyrion',
    groupPriority: 3,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 3,
    def: 3,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'dr',
    name: 'Fire Dragon',
    plural: 'Fire Dragons',
    group: 'Elyrion',
    groupPriority: 3,
    description: '',
    currenthp: 20,
    maxhp: 20,
    vet: false,
    vetNow: false,
    att: 4,
    def: 3,
    bonus: 1,
    fort: false,
    range: true,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'mo',
    name: 'Mooni',
    plural: 'Moonies',
    group: 'Polaris',
    groupPriority: 4,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: true,
    vetNow: false,
    att: 0,
    def: 2,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: false,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'sl',
    name: 'Battle Sled',
    plural: 'Battle Sleds',
    group: 'Polaris',
    groupPriority: 4,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 3,
    def: 2,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'if',
    name: 'Ice Fortress',
    plural: 'Ice Fortresses',
    group: 'Polaris',
    groupPriority: 4,
    description: '',
    currenthp: 20,
    maxhp: 20,
    vet: true,
    vetNow: false,
    att: 4,
    def: 3,
    bonus: 1,
    fort: false,
    range: true,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'sm',
    name: 'Shaman',
    plural: 'Shamans',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: false,
    vetNow: false,
    att: 1,
    def: 1,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'he',
    name: 'Hexapod',
    plural: 'Hexapods',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 5,
    maxhp: 5,
    vet: true,
    vetNow: false,
    att: 3,
    def: 1,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ki',
    name: 'Kiton',
    plural: 'Kitons',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 20,
    maxhp: 20,
    vet: true,
    vetNow: false,
    att: 1,
    def: 3,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: true,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ph',
    name: 'Phychi',
    plural: 'Phychis',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 5,
    maxhp: 5,
    vet: true,
    vetNow: false,
    att: 1,
    def: 1,
    bonus: 1,
    fort: false,
    range: true,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: true,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ex',
    name: 'Exida',
    plural: 'Exidas',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: true,
    vetNow: false,
    att: 3,
    def: 1,
    bonus: 1,
    fort: false,
    range: true,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: true,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'ra',
    name: 'Raychi',
    plural: 'Raychis',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 15,
    maxhp: 15,
    vet: true,
    vetNow: false,
    att: 3,
    def: 2,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: true,
    canExplode: true,
    exploding: false
  },
  {
    code: 'do',
    name: 'Doomux',
    plural: 'Doomuxes',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 20,
    maxhp: 20,
    vet: true,
    vetNow: false,
    att: 4,
    def: 2,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: true,
    canExplode: true,
    exploding: false
  },
  {
    code: 'ce',
    name: 'Centipede',
    plural: 'Centipedes',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 20,
    maxhp: 20,
    vet: false,
    vetNow: false,
    att: 4,
    def: 3,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  },
  {
    code: 'se',
    name: 'Segment',
    plural: 'Segments',
    group: 'Cymanti',
    groupPriority: 1,
    description: '',
    currenthp: 10,
    maxhp: 10,
    vet: false,
    vetNow: false,
    att: 2,
    def: 2,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: false,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: true,
    canExplode: true,
    exploding: false
  },
  {
    code: 'nb',
    name: 'Nature Bunny',
    plural: 'Nature Bunnies',
    group: 'Normal',
    groupPriority: 0,
    description: '',
    currenthp: 20,
    maxhp: 20,
    vet: false,
    vetNow: false,
    att: 5,
    def: 1,
    bonus: 1,
    fort: false,
    range: false,
    retaliation: true,
    forceRetaliation: undefined,
    poisonattack: false,
    poisonexplosion: false,
    canExplode: false,
    exploding: false
  }
]